-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 03:54:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema financial_institutions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financial_institutions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financial_institutions` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `financial_institutions` ;

-- -----------------------------------------------------
-- Table `financial_institutions`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`address` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COUNTRY` VARCHAR(100) NOT NULL,
  `CITY` VARCHAR(120) NOT NULL,
  `LINE1` VARCHAR(150) NOT NULL,
  `ZIP` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`financial_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`financial_network` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `GENERATED_ON` DATE NULL DEFAULT NULL,
  `LAST_UPDATED` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`bank` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(150) NOT NULL,
  `ACTIVE` TINYINT(1) NOT NULL DEFAULT '1',
  `FINANCIAL_NETWORK_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_bank_network` (`FINANCIAL_NETWORK_ID` ASC) VISIBLE,
  CONSTRAINT `fk_bank_network`
    FOREIGN KEY (`FINANCIAL_NETWORK_ID`)
    REFERENCES `financial_institutions`.`financial_network` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`branch` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BANK_ID` INT NOT NULL,
  `ADDRESS_ID` INT NOT NULL,
  `CODE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `BANK_ID` (`BANK_ID` ASC, `CODE` ASC) VISIBLE,
  INDEX `fk_branch_address` (`ADDRESS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_branch_address`
    FOREIGN KEY (`ADDRESS_ID`)
    REFERENCES `financial_institutions`.`address` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_branch_bank`
    FOREIGN KEY (`BANK_ID`)
    REFERENCES `financial_institutions`.`bank` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`customer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BANK_ID` INT NOT NULL,
  `FULL_NAME` VARCHAR(160) NOT NULL,
  `BIRTH_DATE` DATE NULL DEFAULT NULL,
  `ADDRESS_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_customer_bank` (`BANK_ID` ASC) VISIBLE,
  INDEX `fk_customer_address` (`ADDRESS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`ADDRESS_ID`)
    REFERENCES `financial_institutions`.`address` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_bank`
    FOREIGN KEY (`BANK_ID`)
    REFERENCES `financial_institutions`.`bank` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`account_type` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(20) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODE` (`CODE` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`account` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `BRANCH_ID` INT NOT NULL,
  `ACCOUNT_TYPE_ID` INT NOT NULL,
  `IBAN` VARCHAR(34) NOT NULL,
  `BALANCE` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
  `OPENED_ON` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `IBAN` (`IBAN` ASC) VISIBLE,
  INDEX `fk_account_customer` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `fk_account_branch` (`BRANCH_ID` ASC) VISIBLE,
  INDEX `fk_account_type` (`ACCOUNT_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_account_branch`
    FOREIGN KEY (`BRANCH_ID`)
    REFERENCES `financial_institutions`.`branch` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_customer`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `financial_institutions`.`customer` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_type`
    FOREIGN KEY (`ACCOUNT_TYPE_ID`)
    REFERENCES `financial_institutions`.`account_type` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`transaction_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`transaction_type` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(20) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODE` (`CODE` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`account_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`account_transaction` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` INT NOT NULL,
  `TRANSACTION_TYPE_ID` INT NOT NULL,
  `AMOUNT` DECIMAL(18,2) NOT NULL,
  `HAPPENED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_tx_type` (`TRANSACTION_TYPE_ID` ASC) VISIBLE,
  INDEX `idx_tx_account_time` (`ACCOUNT_ID` ASC, `HAPPENED_AT` ASC) VISIBLE,
  CONSTRAINT `fk_tx_account`
    FOREIGN KEY (`ACCOUNT_ID`)
    REFERENCES `financial_institutions`.`account` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tx_type`
    FOREIGN KEY (`TRANSACTION_TYPE_ID`)
    REFERENCES `financial_institutions`.`transaction_type` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`card` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` INT NOT NULL,
  `PAN_MASKED` VARCHAR(25) NOT NULL,
  `EXPIRY` DATE NULL DEFAULT NULL,
  `CONTACTLESS` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `fk_card_account` (`ACCOUNT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_card_account`
    FOREIGN KEY (`ACCOUNT_ID`)
    REFERENCES `financial_institutions`.`account` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`employee` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BRANCH_ID` INT NOT NULL,
  `FULL_NAME` VARCHAR(160) NOT NULL,
  `HIRED_DATE` DATE NULL DEFAULT NULL,
  `MANAGER` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `fk_employee_branch` (`BRANCH_ID` ASC) VISIBLE,
  CONSTRAINT `fk_employee_branch`
    FOREIGN KEY (`BRANCH_ID`)
    REFERENCES `financial_institutions`.`branch` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `financial_institutions`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial_institutions`.`loan` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `BRANCH_ID` INT NOT NULL,
  `PRINCIPAL` DECIMAL(18,2) NOT NULL,
  `RATE` DECIMAL(7,4) NOT NULL,
  `START_DATE` DATE NULL DEFAULT NULL,
  `END_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_loan_customer` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `fk_loan_branch` (`BRANCH_ID` ASC) VISIBLE,
  CONSTRAINT `fk_loan_branch`
    FOREIGN KEY (`BRANCH_ID`)
    REFERENCES `financial_institutions`.`branch` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loan_customer`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `financial_institutions`.`customer` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
